### PR TITLE
[WIP] Add docker

### PR DESCRIPTION
**Pull request by ViViDboarder**
This is definitely a work in progress that I started working on a while back. I know it's in conflict right now, but there were a couple issues that I encountered and thought it was best to discuss how to resolve them rather than patching myself.

The biggest thing is, how to pass values from outside the image into the container? This patch uses environment variables to do so, which works fine with Docker. A lot of applications do that. The other alternative would be to put all variables into a config file.

I'm open to either, but I can't really continue until one option is settled on.

What are your thoughts?

### CODE REVIEW

**Comment by hooram** [comment]
Awesome. It looks great. Using environment variables will work fine I think. What are some of the other issues you encountered?

Since you've forked, I've added some features that require changing the dockerfile as well, namely object recognition and usnig [mapzen](https://mapzen.com) for reverse geolocation. 

## Object recognition

It uses [densecap](https://github.com/hooram/ownphotos-backend/tree/master/densecap), which requires torch/lua to be installed along with its luarocks installs. It also needs a rather big pretrained model file (~1gb as I remember). Since this runs much faster with CUDA enabled, I thought having two versions of dockerfile would be nice: one that uses nvidia-docker for those who have a GPU on their servers, and the other that just uses the ubuntu base image, as you have done. 

We would need to change the dockerfile to install it and include its daemon scripts to entrypoint.sh. A brief instruction is in the project readme (reading that instruction again now, I think I was drunk or something). 

## Reverse Geolocation

I decided to use mapzen for reverse geolocation of photos that have gps information. They require you to have an account to get an api key. You can make 30,000 queries per month with the free tier account, if I remember correctly.  Originally I was using the [nominatim](http://nominatim.openstreetmap.org/) server of openstreetmaps, but after I got my IP blocked from their server I looked for more dependable solutions, and mapzen seemed like a good one. I know this makes it not 100% selfhosted. One could host his own nominatim server, which in my opinion goes beyond the scope of this project. Possibly in the future it would be nice to add support for self hosted nominatim servers. 

We would need to pass the mapzen api key to the container as another environment variable. 

---

The above two are not absolutely necessary, because without object recognition and geolocation the backend/frontend will still work just fine, it's just that some of the charts will be blank and that the user will not be able to search for photos by their contents and locations.

Additionally, I think it's a good idea to keep a separate branch for building docker images for now, and always pull from master into the docker branch. This this way we won't have to worry about conflicts on settings.py and config.py. What do you think?

**Comment by ViViDboarder** [comment]
Thanks for resolving and merging! I also have a front end branch I can submit a PR for. I will admit that frontend is not my strong suit and I encountered a few challenges with host routing between the two. Your implementation seems to expect them on the same box, but if in two different containers, they will be different hosts.

**Comment by hooram** [comment]
No problem! I'm happy that you took the time to contribute. As for the frontend, I actually had in mind that they can be run on different boxes. I'm planning to add a custom server address input in the login page, to explicitly allow the front/backends to run on different machines. Anyways, PRs welcome, and feel free to open issues or anything if you want to discuss something. 

BTW, I ironed out some rough edges in the backend code to build the docker image from your dockerfile and successfully ran a container. But for some odd reason media files (thumbnails and whatnot) are giving 404's. I'm trying to fix this issue; have you encountered something similar when working on the dockerfile?

**Comment by hooram** [comment]
I figured it out: with debug=false, development server does not serve media files.

**Comment by ViViDboarder** [comment]
Perfect! I think in was having the same issue.

**Comment by ViViDboarder** [comment]
Building two docker images shouldn't be too bad. I've been dealing with the same things building for arm and x86 already.

As for including a 1GB model... That's a pretty large file to include. I suppose it could be added as a build step, alternately, it could download to a volume on first run. I'm not sure what best practices are for this, but I can poke around.

**Pull request merged**
